name: ${PROJECT}

services:
        server:
                image: ${PROJECT}-server
                build:
                        context: .
                        dockerfile: Dockerfile.server
                deploy:
                        resources:
                                limits:
                                        memory: 3g

        mysql:
                image: ${PROJECT}-mysql
                build:
                        context: .
                        dockerfile: Dockerfile.mysql
                hostname: mysql
                environment:
                        MYSQL_ROOT_PASSWORD: acid
                        MYSQL_DATABASE: CS544
                healthcheck:
                        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-pacid" ]
                        interval: 5s
                        retries: 10
                volumes:
                        - mysql-data:/var/lib/mysql
                deploy:
                        resources:
                                limits:
                                        memory: 1g
        nn:
                image: ${PROJECT}-nn
                build:
                        context: .
                        dockerfile: Dockerfile.namenode
                hostname: nn
                deploy:
                        resources:
                                limits:
                                        memory: 1g
        dn:
                image: ${PROJECT}-dn
                build:
                        context: .
                        dockerfile: Dockerfile.datanode
                deploy:
                        replicas: 3
                        resources:
                                limits:
                                        memory: 1g

volumes:
        mysql-data:
