FROM ubuntu:24.04

RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*
RUN pip3 install --break-system-packages flask cassandra-driver pytest requests

COPY server2.py rest_test.py /

CMD ["python3", "-u", "server2.py"]
