FROM p4-hdfs
RUN pip3 install --break-system-packages grpcio grpcio-tools sqlalchemy mysql-connector-python
COPY lender.proto /
RUN python3 -m grpc_tools.protoc -I/ --python_out=/ --grpc_python_out=/ /lender.proto
COPY client.py /
CMD ["sleep", "infinity"]
