FROM ubuntu:22.04
RUN apt-get update && apt-get install -y wget
RUN wget https://huggingface.co/Mozilla/gemma-3-4b-it-llamafile/resolve/main/google_gemma-3-4b-it-Q6_K.llamafile
RUN chmod +x google_gemma-3-4b-it-Q6_K.llamafile
CMD ["bash", "-c", "./google_gemma-3-4b-it-Q6_K.llamafile"]
